### ISSUE TITLE
[Feature]: Support pulling images from private Docker registries 

### ISSUE THREAD

**Issue by robe-rt** [dataphos/dataphos-helm#5]
## Description

This feature would allow users to deploy Dataphos components using Docker images from private registries.

## Problem to Solve

In the current state, if the users want to deploy the components using Docker images from private registries, there is no other way but to create a Kubernetes secret manually and edit the pods to use it. This feature would allow the user to specify private Docker registry credentials which would be automatically passed as a secret to the pods that need them. 

## Proposed Solution

The user would list multiple private Docker registry credentials in the `values.yaml` files of the Helm charts like this:

```
registryCredentials:
- registry: first_registry
  username: username
  password: password
- registry: second_registry
  username: username
  password: password
```

These credentials would be used to create Kubernetes secrets used in pods to pull images. The user needs to be able to use an image from a different private Docker registry for each component inside of a single product:

```
images:
  initdb: syntioinc/dataphos-schema-registry-initdb:1.0.0
  registry: hub.syntio.xyz/jaintor/api:v1.0.0
  compatibilityChecker: scratch.hub.syntio.xyz/janitor/compatibilitychecker:v1.0.0
  validityChecker: syntioinc/dataphos-schema-registry-validity:1.0.0
```

## Alternatives Considered

Currently, there are no alternative solutions I've considered because I see this solution as adequate.

## Additional Context

The motivation for this feature is the need to use images from our internal private Nexus repository we use for development and testing purposes.
